### ISSUE TITLE
Revue mi-project

### ISSUE THREAD

**Issue by SpicyPaper** [HE-Arc/sparty#51]
Vous avez une bonne base avec une bonne structure de MVC avec un service Spotify qui a l'air de bien fonctionner (bonne idée et bonne implémentation pour le service). Vous avez écrit ou reprit le service Spotify d'un autre cours ?

Bonne base de projet donc, mais il y a encore du travail en backend, surtout en frontend.

Continuez comme ça :)

**Comment by ulysg** [comment]
Le service Spotify est basé sur une classe faite pour un ancien projet de dev web, mais totalement réécrite et avec une structure très différente.
